# Generated by Django 4.2.3 on 2023-07-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass',
            options={'verbose_name_plural': 'Pass'},
        ),
        migrations.RenameField(
            model_name='pass',
            old_name='roll_number',
            new_name='reg_number',
        ),
    ]
