# Generated by Django 4.2.3 on 2023-07-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pass_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='bio_id',
            field=models.IntegerField(),
        ),
    ]
