# Generated by Django 4.2.3 on 2023-07-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pass_bio_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pass',
            old_name='name',
            new_name='student_name',
        ),
    ]
