# Generated by Django 4.2.3 on 2023-07-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_pass_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pass',
            old_name='year_of_study',
            new_name='year',
        ),
    ]
