# Generated by Django 4.2.3 on 2023-07-29 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pass_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='id',
        ),
        migrations.AlterField(
            model_name='pass',
            name='bio_id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(40000)]),
        ),
    ]
