# Generated by Django 4.2.3 on 2023-07-29 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_pass_id_alter_pass_bio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='bio_id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(30000), django.core.validators.MaxValueValidator(40000)]),
        ),
    ]
