# Generated by Django 4.2.3 on 2023-07-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pass_bio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='transport_route',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
