# Generated by Django 4.2.3 on 2023-08-05 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_pass_transport_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^\\d{1,2}-\\d{1,2}-\\d{4}$')])),
            ],
            options={
                'verbose_name_plural': 'ScanLogs',
            },
        ),
    ]
