# Generated by Django 4.2.3 on 2023-08-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_scanlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='student_list',
            field=models.ManyToManyField(to='api.pass'),
        ),
    ]
