# Generated by Django 4.2.3 on 2023-08-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_scanlog_student_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanlog',
            name='student_list',
        ),
    ]
