# Generated by Django 4.2.3 on 2023-08-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_scanlog_student_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='student_list',
            field=models.ManyToManyField(to='api.pass'),
        ),
    ]
