# Generated by Django 4.2.3 on 2023-08-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ScanUser',
        ),
    ]
