# Generated by Django 4.2.3 on 2023-08-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_user_scanuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScanUser',
            new_name='User',
        ),
    ]
