# Generated by Django 4.2.3 on 2023-08-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_transport_pass_istransport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='valid_upto',
        ),
        migrations.AddField(
            model_name='pass',
            name='valid_upto_bus',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='valid_upto_hostel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pass',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='institution',
            field=models.CharField(choices=[('SIMATS', 'SIMATS'), ('SEC', 'SEC'), ('AHS', 'AHS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pass',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV,', 'IV')], max_length=20),
        ),
    ]
