# Generated by Django 4.2.3 on 2023-08-11 02:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_pass_valid_upto_pass_valid_upto_bus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanlog',
            name='student_list',
        ),
        migrations.AddField(
            model_name='scanlog',
            name='bio_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.pass'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='scan_time',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}:\\d{2}:\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='scan_date',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,2}-\\d{1,2}-\\d{4}$')]),
        ),
    ]
