# Generated by Django 4.2.3 on 2023-08-11 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_scanlog_student_list_scanlog_bio_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='bio_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.pass'),
        ),
    ]
