# Generated by Django 4.2.3 on 2023-08-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_scanlog_bio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='isHostel',
        ),
        migrations.AddField(
            model_name='scanlog',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='isTransport',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='student_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
