# Generated by Django 4.2.3 on 2023-08-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_pass_ishostel_scanlog_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='isHostel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='student_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='pass',
            unique_together={('bio_id', 'student_name')},
        ),
    ]
