# Generated by Django 4.2.3 on 2023-08-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_scanlog_ishostel_alter_scanlog_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='student_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
