# Generated by Django 4.2.3 on 2023-08-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_scanlog_student_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pass',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='scanlog',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='scanlog',
            name='isHostel',
        ),
        migrations.RemoveField(
            model_name='scanlog',
            name='isTransport',
        ),
        migrations.RemoveField(
            model_name='scanlog',
            name='student_name',
        ),
        migrations.AddField(
            model_name='pass',
            name='isHostel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='isTransport',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
