# Generated by Django 4.2.3 on 2023-08-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_pass_unique_together_remove_scanlog_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='isHostel',
            field=models.BooleanField(null=True,blank=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='isTransport',
            field=models.BooleanField(null=True,blank=True),
        ),
    ]
