# Generated by Django 4.2.3 on 2023-09-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_pass_ishostel_alter_pass_istransport'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
