# Generated by Django 4.2.3 on 2023-10-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_sessiontable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiontable',
            name='refresh_token',
        ),
    ]
